echo Y | copy draugrmale01_naked.nif draugrmale.nif
echo Y | copy draugrmale.nif draugrmale01.nif
echo Y | copy draugrmale.nif draugrmale02.nif
echo Y | copy draugrmale.nif draugrmale03.nif
echo Y | copy draugrmale.nif draugrmale04.nif
echo Y | copy draugrmale.nif draugrmale05.nif
echo Y | copy draugrmale.nif draugrmale06.nif
echo Y | copy draugrmale.nif draugrmale07.nif
echo Y | copy draugrmale.nif hulkingdraugr.nif
